;;; Elfeed score file                                     -*- lisp -*-
((version 10)
 ("title")
 ("content")
 ("title-or-content"
  (:text "ODE" :title-value 100 :content-value 20 :type s)
  (:text "Hamiltonian Monte Carlo" :title-value 100 :content-value 20 :type s)
  (:text "Bayesian" :title-value 100 :content-value 20 :type s)
  (:text "kinetic model" :title-value 100 :content-value 20 :type s)
  (:text "allosteric" :title-value 100 :content-value 20 :type s)
  (:text "escherichia" :title-value 100 :content-value 20 :type s)
  (:text "Michaelis" :title-value 100 :content-value 20 :type s)
  (:text "Gibbs energy change" :title-value 100 :content-value 20 :type s)
  (:text "Stan" :title-value 100 :content-value 20 :type S))
 ("tag")
 ("authors"
  (:text "Andrew Gelman" :value 300 :type S)
  (:text "Michael Betancourt" :value 300 :type S)
  (:text "Aki Vehtari" :value 300 :type S)
  (:text "Tamara Broderick" :value 300 :type S)
  (:text "Lars Keld Nielsen" :value 300 :type S)
  (:text "Jens Nielsen" :value 300 :type S)
  (:text "Elaad Noor" :value 300 :type S)
  (:text "Susan Holmes" :value 300 :type S)
  (:text "Bernhard Pallson" :value 300 :type S))
 ("feed")
 ("link")
 ("udf")
 (mark -600)
 ("adjust-tags"))
